config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # To get a complete list of the available routes in your application, 
  # visit http://localhost:3000/rails/info/routes in your browser while your server 
  # is running in the development environment. You can also execute the `rails routes` 
  # command in your terminal to produce the same output.

  # `devise_for` is responsible to generate all needed routes for devise, 
  # based on what modules you have defined in your model.

  devise_scope :user do
    root 'users/sessions#show'
  end

  mount ActionCable.server => '/cable'

  devise_for :users, 
  path_names: {
    sign_in: 'login', 
    sign_out: 'logout'
  }, 
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # The devise_for method is going to look inside your User model and create the
    # needed routes:

    # new_user_session          GET    /users/login(.:format)             users/sessions#new
    # user_session              POST   /users/login(.:format)             users/sessions#create
    # destroy_user_session      DELETE /users/logout(.:format)            users/sessions#destroy
    # new_user_password         GET    /users/password/new(.:format)      users/passwords#new
    # edit_user_password        GET    /users/password/edit(.:format)     users/passwords#edit
    # user_password             PATCH  /users/password(.:format)          users/passwords#update
    #                           PUT    /users/password(.:format)          users/passwords#update
    #                           POST   /users/password(.:format)          users/passwords#create
    # cancel_user_registration  GET    /users/cancel(.:format)            users/registrations#cancel
    # new_user_registration     GET    /users/sign_up(.:format)           users/registrations#new
    # edit_user_registration    GET    /users/edit(.:format)              users/registrations#edit
    # user_registration         PATCH  /users(.:format)                   users/registrations#update
    #                           PUT    /users(.:format)                   users/registrations#update
    #                           DELETE /users(.:format)                   users/registrations#destroy
    #                           POST   /users(.:format)                   users/registrations#create
    # new_user_confirmation     GET    /users/confirmation/new(.:format)  users/confirmations#new
    # user_confirmation         GET    /users/confirmation(.:format)      users/confirmations#show
    #                           POST   /users/confirmation(.:format)      users/confirmations#create

    # user_twitter_omniauth_authorize GET|POST /users/auth/twitter(.:format)          users/omniauth_callbacks#passthru
    # user_twitter_omniauth_callback  GET|POST /users/auth/twitter/callback(.:format) users/omniauth_callbacks#twitter

  get '/users/:id', to: 'users/rest#show', as: 'user'

  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  scope 'projects' do
    scope 'catelog' do
      get '/search', to: 'project_variations#search', as: 'search_projects'
      get '/new-projects', to: 'project_variations#new_projects', as: 'newly_created_projects'
      get '/popular-projects', to: 'project_variations#popular_projects', as: 'popular_projects'
      get '/fully-funded', to: 'project_variations#fully_funded', as: 'fully_funded_projects'
      get '/film-types', to: 'project_variations#film_types_projects', as: 'film_types_projects'
      get '/film-types/:type', to: 'project_variations#film_type', as: 'film_type_projects'
    end
  end

  get '/genres', to: 'genres#index'
  get '/genres/:name', to: 'genres#show', as: "genre"
  
  resources :comments, only: [:create, :update, :destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :description, :goal, presence: true
  validates :name, uniqueness: true
  validates :goal, numericality: { greater_than_or_equal_to: 0 }

  validate :acceptable_genre?, :acceptable_film_type?
  before_destroy :donations_prevents_deletion?

  # before_destroy -> When donations are created, projects will no longer be allowed
  # to be destroyed if there are donations on the project.

  belongs_to :user
  has_one_attached :cover_image
  has_one_attached :script
  has_many :comments
  has_many :donations

  monetize :goal_cents, allow_nil: false, numericality: { 
    greater_than_or_equal_to: 0, 
    less_than_or_equal_to: 1000000
  }

  @@genres = {
    :action=>"Action", :adventure=>"Adventure", biopic: "Biopic", 
    :comedy=>"Comedy", :crime=>"Crime", :drama=>"Drama", :fantasy=>"Fantasy", 
    :historical=>"Historical", :horror=>"Horror", :mystery=>"Mystery", noir: "Noir", 
    :philosophical=>"Philosophical", :political=>"Political", :romance=>"Romance", 
    :satire=>"Satire", :science_fiction=>"Science Fiction", :silent=>"Silent", 
    :social=>"Social", :thriller=>"Thriller", :urban=>"Urban", :western=>"Western"
  }

  @@film_types = {
    advertisement: "Advertisement", animation: "Animation", 
    documentary: "Documentary", feature: "Feature", short: "Short",
    episodic: "Episodic"
  }

  def self.genres
    @@genres
  end

  def self.film_types
    @@film_types
  end

  scope :newly_created, -> { order(created_at: :desc) }
  scope :fully_funded, -> { includes(:user).where(goal_cents: 0) }

  def self.most_popular
    joins(:comments)
    .select("projects.*, count(comments.id) AS comments_count")
    .group("projects.id").
    order("comments_count DESC")
  end

  def acceptable_film_type?
    if !@@film_types.has_key?(self.film_type.downcase.to_sym) 
      errors.add(:film_type, "invalid type")
    end
  end

  def acceptable_genre?
    if !@@genres.has_key?(self.genre.downcase.to_sym) 
      errors.add(:genre, "invalid category")
    end
  end

  def donations_prevents_deletion?
    if self.donations.count > 0
      errors.add(:goal_cents, "Project cannot be deleted due to donations")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @project_info = "index"
    @projects = Project.includes(:user, {cover_image_attachment: :blob}).last(10)
    render "project_variations/shared_project_variations"
  end

  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    if @project.valid?
      @project.save
      redirect_to project_path(@project)
    else
      redirect_to new_project_path
    end
  end

  def show
    find_project_by_id
    show_comments?
  end

  def edit
    find_project_by_id
  end

  def update
    find_project_by_id
    current_user_project?
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      redirect_to project_path(@project)
    end
  end

  def destroy
    find_project_by_id
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(
      :name,
      :description,
      :goal,
      :film_type,
      :genre,
      :story_structure,
      :themes,
      :link,
      :user_id,
      :cover_image,
      :script
    )
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def find_project_by_id
    @project = Project.find_by_id(params[:id])
    redirect_to projects_path if @project.nil?
  end

  def current_user_project?
    current_user.id.equal?(@project.user_id)
  end

  def show_comments?
    @comments = @project.comments.includes(:user).last(10).reverse if !@project.nil?
  end
end

app/views/projects/_form.html.erb
<div>
  <%= f.label :cover_image %>
  <%= f.file_field :cover_image, accept: 'image/png,image/gif,image/jpeg' %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "Description" %>
</div>

<div>
  <%= f.label :film_type %>
  <% # collection_select(method, collection, value_method, text_method, options = {}, html_options = {})%>
  <%= f.collection_select :film_type, Project.film_types, :last, :last%>
</div>

<div>
  <%= f.label :genre %>
  <%= f.collection_select :genre, Project.genres, :last, :last%>
</div>

<div>
  <%= f.label :story_structure %>
  <%= f.text_field :story_structure, placeholder: "3 Act Structure" %>
</div>

<div>
  <%= f.label :themes %>
  <%= f.text_field :themes, placeholder: "symbolism" %>
</div>

<div>
  <%= f.label :script %>
  <%= f.file_field :script, accept: ".pdf, .doc" %>
</div>

<div>
  <%= f.label :link %>
  <%= f.text_field :link, placeholder: "Project video, website, etc." %>
</div>

app/views/projects/edit.html.erb
<main>
  <section>
    <h2>Edit: <%= @project.name %></h2>
    <div>
      <%= form_with model: @project, class: "new-project-form" do |f| %>
        <%= render partial: 'form', locals: {f: f} %>
        <div>
          <%= f.submit "Submit" %>
        </div>
      <% end %>
    </div>
  </section>

  <section>
    <h2>Delete <%= @project.name %>?</h2>
    <p><%= link_to  "Permanently Delete Project", @project, method: :delete %></p>
  </section>
</main>

app/views/projects/index.html.erb
<main>
  <% @projects.each do |project|%>
    <section>
      <h2><%= link_to project.name, project, data: {turbolinks: "false"} %></h2>
      <p><%=project.description%></p>
      <p><%=project.film_type%></p>
      <p><%=project.user.display_name%></p>
    </section>
  <% end %>
</main>

app/views/projects/new.html.erb
<main>
  <h2>Create New Project</h2>
  <div>
    <%= form_with model: @project, class: "new-project-form" do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Name" %>
      </div>

      <div>
        <%= f.label :goal %>
        <%= f.number_field :goal, placeholder: "Goal" %>
      </div>

      <%= render partial: 'form', locals: {f: f} %>

      <div>
        <%= f.submit "Submit" %>
      </div>
    <% end %>
  </div>
</main>

app/views/projects/show.html.erb
<main>
  <div id="flex-project-media-comments-container">

    <article id="project-media-container">
      <section id="media-container">
        <div>
          <% if !@project.link.blank? %>
            <div id="iframe-container">
              <iframe id="project-link" src=<%= @project.link %>></iframe>
            </div>
          <% else %>
            <% if @project.cover_image.attached?%>
              <div 
                id="background-image" 
                style="background-image: url('<%= rails_blob_url(@project.cover_image) %>');">
              </div>
            <% else %>
              <div 
                id="background-image" 
                style="background-image: url('<%= asset_path 'hacker_wallpaper.jpg' %>');">
              </div>
            <% end %>
          <% end %>
        </div>
      </section>
    </article>

    <article id="comments-container">
      <div id="comments-align">

        <section id="form-container">
          <%= form_with model: Comment.new do |f| %>
            <%= render partial: "comments/new", locals: {f: f, project: @project} %>
            <div id="submit-container">
              <%= f.submit "Submit", id: "comment-submit" %>
            </div>
          <% end %>
        </section>

        <section id="comments">
          <h3>Comments:</h3>
          <% if @comments %>
            <% @comments.each do |comment|%>
              <%= render partial: "comments/comment", locals: {comment: comment} %>
            <% end %>
          <% end %>
        </section>

      </div>
    </article>
  </div>

  <article id="project-info">
    <section>
      <div id="title-author">
        <h1><%= @project.name %></h1>
        <p>By <%=@project.user.display_name%></p>
      </div>

      <div id="name-goal-filmtype">
        <% if current_user_project? %>
          <p><%= link_to  "Edit", edit_project_path(@project) %></p>
        <% end %>
        <p>Film Type: <%= @project.film_type %></p>
        <p>Original Goal: <%= humanized_money_with_symbol @project.goal %></p>
        <p>Donations: </p>
        <p>Remaining:</p>
      </div>
    </section>

    <section id="project-info-container">
      <div>
        <h2>Description:</h2>
        <p><%= @project.description %></p>
      </div>

      <div>
        <h2>Story Structure:</h2>
        <p><%= @project.story_structure %></p>
      </div>

      <div>
        <h2>Themes:</h2>
        <p><%= @project.themes %></p>
      </div>
    </section>

  </article>
</main>